### PR TITLE
[fix] singleton in SessionStore

### PR DESCRIPTION
**Pull request by anistal**
Singleton in sessionstore should be used by all instances that needs to authenticate.

### CODE REVIEW

**Comment by ccaballe** [comment]
+1 Good job!

**Comment by arinconstrio** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Comment by mpenate** [comment]
Deleted shipit comments, there was an error with repo permissions. Here  we go once again beloved squirrel.

**Comment by mpenate** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP

**Comment by stratiocommit** [comment]
Squashing and checks in progress.

**Pull request merged**
